spring:
  mvc:
    view:
      prefix: WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/votesys
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true

  mail:
    host: smtp.qq.com
    username: 212269061@qq.com
    password: iczenjtgppyibheb
    default-enccoding: UTF-8
mail:
  fromMail:
    addr: 212269061@qq.com

server:
  port: 80